#!/bin/bash

export working_dir=$(pwd)
cd $(dirname $0)


source "$working_dir/vdevrc/vm"
source "$working_dir/vdevrc/paths"
source detail/utils


target=$1
configuration=$2

detail/"$vm"/execute "$guest_build_bat" "$vs_version" "$guest_solution_path" "$target" "$configuration" "$guest_build_log_path"
retval=$?
printf '\n'

exit $retval

