#!/bin/bash

export working_dir=$(pwd)
cd $(dirname $0)
export vdevrc_dir="$working_dir/vdevrc"


source "$vdevrc_dir/vm"
source "$vdevrc_dir/conf"
source detail/utils


#
# Parameters

solution_path=$1
target=$2
configuration=$3


#
# Main

vs_version=$(detail/vsversion "$working_dir/$solution_path")

guest_solution_path="$guest_root_dir/$solution_path"
detail/"$vm"/execute "$guest_build_bat" "$vs_version" "$guest_solution_path" "$target" "$configuration"
retval=$?
printf '\n'

exit $retval

