#!/bin/bash

if [ -z "$VIRTUAL_DEV" ]
then
	export VIRTUAL_DEV=$(dirname $0)
fi

export VIRTUAL_DEV_WORKING_DIR=$PWD

source "$VIRTUAL_DEV"/detail/constants
source "$VIRTUAL_DEV"/detail/utils
source "$VIRTUAL_DEV"/detail/dictionary


export VIRTUAL_DEV_WORKSPACE_DIR="$VIRTUAL_DEV_WORKING_DIR/$VIRTUAL_DEV_WORKSPACE"

if [ ! -d "$VIRTUAL_DEV_WORKSPACE_DIR" ]
then
	printf-vdev-error 'current path doesn'"'"'t have any virtual-dev workspace'
	exit 1
fi


HELP_MESSAGE=\
'Runs executable in guest machine

Usage:
    vdev-execute <working-dir> <executable> [<parameters>...]
    vdev-execute -h | --help

Parameters:
    <working-dir>  Working directory for executable.
    <executable>   Executable name or path.
    <parameters>   Parameters for executable.
    -h | --help    Show this message
'


#
# Parameters

working_dir=$1
binary_path=$2
arguments=("${@:3}")


#
# Main

vdev_vm_file="$VIRTUAL_DEV_WORKSPACE_DIR/$VIRTUAL_DEV_VM_FILE"
dictionary-load "$vdev_vm_file" 'vm' 'guest_name'


# Checks

if [ $# == 1 ] && ([ $1 == '-h' ] || [ $1 == '--help' ])
then
	printf '%s\n' "$HELP_MESSAGE"
	exit
fi

if [ $# \< 2 ]
then
	printf-vdev-error 'too few arguments\nUse '"'"'-h'"'"' or '"'"'--help'"'"' to get help'
	exit 1
fi


# Paths file

vdev_guest_paths_file="$VIRTUAL_DEV_WORKSPACE_DIR/$VIRTUAL_DEV_GUEST_PATHS_FILE"

"$VIRTUAL_DEV"/detail/check-paths-file "$vdev_guest_paths_file"
if [ $? == 2 ]
then
	printf-vdev-warning 'shared disk on "%s" for this workspace was changed.' "$guest_name"
fi

dictionary-load "$vdev_guest_paths_file" 'guest_root_dir' 'guest_execute_bat'


# Execution

trap "$VIRTUAL_DEV/detail/terminate $binary_name" INT

# passing arguments through environment variable, because some commands may remove characters like "=" from arguments like "/property:configuration=Release"
export VIRTUAL_DEV_ARGUMENTS="${arguments[@]}"
"$VIRTUAL_DEV"/detail/"$vm"/execute "$guest_execute_bat" "$working_dir" "$binary_path"

