#!/bin/bash

export working_dir=$(pwd)
cd $(dirname $0)


source detail/utils


help_message=\
'Usage:
	./init [solution_path] [guest_name] [user] [password]
'


if [ $# -ne 4 ]
then
	print_vdev_error 'wrong number of arguments\n%s\n' "$help_message"
	exit 1
fi


#
# Parameters & variables
export solution_path=$1
export guest_name=$2
export user=$3
export password=$4

project_root="$working_dir"

if [ ! -f "$project_root/$solution_path" ]
then
	print_vdev_error '"%s" does not exist' "$solution_path"
	exit 1
fi

# for future extensibility
VirtualBox=VBoxManage
export vm="VirtualBox"
export vm_manage=$(which "${!vm}")

solution_file_name=$(basename "$solution_path")
solution_dir=$(dirname "$solution_path")
project_name=${solution_file_name%.*}
vs_version=$(detail/vsversion "$project_root/$solution_path")


#
# VirtualBox shared folder
printf 'Creating working directory on \"%s\"...\n' "$guest_name"
try detail/"$vm"/sharedfolder "$project_name" "$project_root" 1> /dev/null
catch print_vdev_error "failed to create shared folder"

printf 'Waiting for \"%s\" to start...\n' "$guest_name"
try detail/"$vm"/startvm
catch print_vdev_error "failed to start \"$guest_name\""

printf 'Waiting for "net" to be available (requires \"%s\" to login)...\n' "$user"
output=$(try detail/finddisk "$project_root")
catch print_vdev_error "failed to find shared disk with project"

guest_shared_disk="$output"


#
# Configuration
printf 'Creating configuration...\n'

vdevrc_dir_path="$project_root/vdevrc"
rm -rf "$vdevrc_dir_path"
mkdir "$vdevrc_dir_path"

cp -R guest "$vdevrc_dir_path/"

vdevrc_vm="$vdevrc_dir_path/vm"

conf_add "$vdevrc_vm" 'vm' "$vm"
conf_add "$vdevrc_vm" 'vm_manage' "$vm_manage"
conf_add "$vdevrc_vm" 'guest_name' "$guest_name"
conf_add "$vdevrc_vm" 'user' "$user"
conf_add "$vdevrc_vm" 'password' "$password"


vdevrc_paths="$vdevrc_dir_path/paths"

conf_add "$vdevrc_paths" 'vs_version' "$vs_version"
conf_add "$vdevrc_paths" 'solution_path' "$solution_path"
conf_add "$vdevrc_paths" 'solution_dir' "$solution_dir"

conf_add "$vdevrc_paths" 'guest_root_dir' "$guest_shared_disk"
conf_add "$vdevrc_paths" 'guest_solution_dir' '$guest_root_dir/'"$solution_dir"
conf_add "$vdevrc_paths" 'guest_solution_path' '$guest_root_dir/'"$solution_path"
conf_add "$vdevrc_paths" 'guest_vdev_guest_dir' '$guest_root_dir/vdevrc/guest/'
conf_add "$vdevrc_paths" 'guest_vsprojprop_bat' '$guest_vdev_guest_dir/vsprojprop.bat'
conf_add "$vdevrc_paths" 'guest_build_bat' '$guest_vdev_guest_dir/build.bat'
conf_add "$vdevrc_paths" 'guest_run_bat' '$guest_vdev_guest_dir/run.bat'


printf 'Done\n'

