#!/bin/bash

source vdev/conf/vm
source vdev/conf/paths
source vdev/detail/utils

target=$1
configuration=$2

out_dir=$(try vdev/detail/vsprojprop "$solution_path" "$target" "$configuration" "OutDir")
catch print_vdev_error "failed to get property"

name=$(try vdev/detail/vsprojprop "$solution_path" "$target" "$configuration" "TargetName")
catch print_vdev_error "failed to get property"

extension=$(try vdev/detail/vsprojprop "$solution_path" "$target" "$configuration" "TargetExt")
catch print_vdev_error "failed to get property"

binary_name="$name$extension"

try vdev/detail/execute "$guest_name" "$user" "$password" "$guest_run_bat" "$guest_solution_dir" "$out_dir" "$binary_name"
catch print_vdev_error "failed to run target \"$target\" ($configuration)"

