#!/bin/bash

export working_dir=$(pwd)
cd $(dirname $0)


source "$working_dir/vdevrc/vm"
source "$working_dir/vdevrc/conf"
source detail/utils
source detail/dictionary


solution_path=$1
target=$2
configuration=$3


solution_dir=$(dirname "$solution_path")
solution_info_dir=$(sln_info_dir_name "$solution_path")

vs_version=$(cat "$working_dir/vdevrc/$solution_info_dir/vs_version")

solution_cache="$working_dir/vdevrc/$solution_info_dir/solution.cache"
detail/loadprojpaths "$working_dir/$solution_path" "$solution_cache"

project_relative_path=$(dictionary_find "$solution_cache" "$target")
project_path="$working_dir/$solution_dir/$project_relative_path"
project_dir=$(dirname "$project_relative_path")

properties_path="$working_dir/vdevrc/$solution_info_dir/$target.$configuration.properties"
detail/loadprojprops "$vs_version" "$solution_dir" "$project_path" "$configuration" "$properties_path"
source "$properties_path"

binary_name="$name$extension"
detail/"$vm"/execute "$guest_run_bat" "$guest_root_dir/$solution_dir/$project_dir" "$out_dir" "$binary_name"
retval=$?
printf "\n" # if put newline in Windows then it can be swallowed

exit $retval

