#!/bin/bash

source "$VIRTUAL_DEV"/detail/constants
source "$VIRTUAL_DEV"/detail/dictionary


#
# Main

dictionary-load "$VIRTUAL_DEV_WORKSPACE_DIR/$VIRTUAL_DEV_VM_FILE" 'vm' 'vm_manage' 'guest_name'


if "$VIRTUAL_DEV"/detail/"$vm"/is-running "$guest_name"
then
	exit
fi

"$vm_manage" startvm "$guest_name" 1> /dev/null
if [ $? != 0 ]
then
	exit 1
fi


while [ true ]
do
	"$VIRTUAL_DEV"/detail/"$vm"/execute 'net.exe' 'accounts' &> /dev/null
	if [ $? == 0 ]
	then
		break
	fi

	sleep 2
done

