#!/bin/bash

source detail/constants
source detail/dictionary


#
# Main

dictionary-load "$VIRTUAL_DEV_WORKSPACE_DIR/$VM_FILE" 'vm' 'vm_manage' 'guest_name'


if detail/"$vm"/is-running "$guest_name"
then
	exit
fi

"$vm_manage" startvm "$guest_name" 1> /dev/null
if [ $? != 0 ]
then
	exit 1
fi


while [ true ]
do
	detail/"$vm"/execute 'net.exe' 'accounts' &> /dev/null
	if [ $? == 0 ]
	then
		break
	fi

	sleep 2
done

