#!/bin/bash

source detail/utils
source detail/dictionary


#
# Parameters

executable_path=$1


#
# Main

dictionary-load "$vdev_dir/vm" 'vm_manage' 'guest_name' 'user' 'password'

executable_name=$(basename "$executable_path")

"$vm_manage" guestcontrol "$guest_name" run --exe "$executable_path" --username "$user" --password "$password" --wait-stdout --wait-stderr --putenv virtual_dev_arguments="$virtual_dev_arguments" "$executable_name" "${@:2}"

