#!/bin/bash

source detail/dictionary


#
# Parameters

guest_name=$1


#
# Main

dictionary-load "$vdev_dir/vm" 'vm_manage' 'guest_name'

running_vms=$("$vm_manage" list runningvms)
grep --quiet "\"$guest_name\".*" <<< "$running_vms"

