#!/bin/bash

source "$VIRTUAL_DEV"/detail/constants
source "$VIRTUAL_DEV"/detail/dictionary


#
# Parameters

guest_name=$1


#
# Main

dictionary-load "$VIRTUAL_DEV_WORKSPACE_DIR/$VM_FILE" 'vm_manage' 'guest_name'

running_vms=$("$vm_manage" list runningvms)
grep --quiet "\"$guest_name\".*" <<< "$running_vms"

