#!/bin/bash

source "$VIRTUAL_DEV"/detail/constants
source "$VIRTUAL_DEV"/detail/utils
source "$VIRTUAL_DEV"/detail/dictionary


#
# Parameters

name=$1
path=$2


#
# Main

dictionary-load "$VIRTUAL_DEV_WORKSPACE_DIR/$VIRTUAL_DEV_VM_FILE" 'vm_manage' 'guest_name'

# if there is a shared folder already VBoxManage prints message, but returns without error
output=$("$vm_manage" sharedfolder add "$guest_name" --name "$name" --hostpath "$path" --automount 2>&1)
retval=$?
if [ $retval != 0 ]
then
	printf-stderr '%s\n' "$output"
	exit $retval
fi

