#!/bin/bash

source vdev/detail/utils
source_existing "vdev/conf/vm"


"$vm_manage" startvm "$guest_name" 1> /dev/null || exit 1

checkstr="running"

while [ true ]
do
	output=$(vdev/detail/"$vm"/execute "echo $checkstr" 2> /dev/null)
	if [ $? -eq 0 ] && [ "$output" = "$checkstr" ]
	then
		break
	fi

	sleep 2
done

