#!/bin/bash

source detail/utils
source detail/dictionary


#
# Main

dictionary-load "$vdev_dir/vm" 'vm' 'vm_manage' 'guest_name'

"$vm_manage" startvm "$guest_name" 1> /dev/null || exit 1

while [ true ]
do
	output=$(detail/"$vm"/execute 'cmd.exe' '/Q' '/C' 'echo' "$checkstr" 2> /dev/null | trim-eoln)
	if [ $? == 0 ] && [ "$output" == "$checkstr" ]
	then
		break
	fi

	sleep 2
done

