#!/bin/bash

source detail/utils
source "$vdev_dir/vm"


#
# Main

"$vm_manage" startvm "$guest_name" 1> /dev/null || exit 1

checkstr='running'

while [ true ]
do
	output=$(detail/"$vm"/execute 'cmd.exe' '/Q' '/C' 'echo' "$checkstr" 2> /dev/null | trim_eoln)
	if [ $? == 0 ] && [ "$output" == "$checkstr" ]
	then
		break
	fi

	sleep 2
done

