#!/bin/bash

source detail/constants
source detail/dictionary


#
# Main

dictionary-load "$VIRTUAL_DEV_WORKSPACE_DIR/$VM_FILE" 'vm_manage'

version=$("$vm_manage" --version)
printf '%s\n' "${version:0:1}"

