#!/bin/bash

source detail/constants
source detail/dictionary


#
# Parameters

guest_name=$1


#
# Main

dictionary-load "$VIRTUAL_DEV_WORKSPACE_DIR/$VM_FILE" 'vm_manage'

vms=$("$vm_manage" list vms)
grep --quiet "\"$guest_name\".*" <<< "$vms"

