#!/bin/bash

source "$VIRTUAL_DEV"/detail/constants
source "$VIRTUAL_DEV"/detail/dictionary


#
# Parameters

guest_name=$1


#
# Main

dictionary-load "$VIRTUAL_DEV_WORKSPACE_DIR/$VIRTUAL_DEV_VM_FILE" 'vm_manage'

vms=$("$vm_manage" list vms)
grep --quiet "\"$guest_name\".*" <<< "$vms"

