#!/bin/bash

source detail/dictionary


#
# Parameters

guest_name=$1


#
# Main

dictionary_load "$vdev_dir/vm" 'vm_manage'

vms=$("$vm_manage" list vms)
grep --quiet "\"$guest_name\".*" <<< "$vms"

