#!/bin/bash

source detail/utils
source detail/dictionary


#
# Parameters

vs_version=$1
solution_dir=$2
project_path=$3
configuration=$4
properties_path=$5


#
# Main

check_dir $(dirname "$properties_path")

if [ ! "$project_path" -nt "$properties_path" ]
then
	exit
fi

rm -f "$properties_path"

out_dir=$(detail/project_property "$vs_version" "$solution_dir" "$project_path" "$configuration" 'OutDir') || exit
out_dir=$(escape_backslashes "$out_dir")

name=$(detail/project_property "$vs_version" "$solution_dir" "$project_path" "$configuration" 'TargetName') || exit

extension=$(detail/project_property "$vs_version" "$solution_dir" "$project_path" "$configuration" 'TargetExt') || exit

conf_add "$properties_path" 'out_dir' "$out_dir"
conf_add "$properties_path" 'name' "$name"
conf_add "$properties_path" 'extension' "$extension"

