#!/bin/bash

source detail/utils
source detail/dictionary


#
# Parameters

solution_path=$1
solution_cache=$2


#
# Main

check_dir $(dirname "$solution_cache")

if [ ! "$solution_path" -nt "$solution_cache" ]
then
	exit
fi

printf 'Caching "%s" info...\n' "${solution_path#$working_dir/}"

version=$(detail/vs_version "$solution_path")
dictionary_insert "$solution_cache" 'version' "$version"

projects=$(grep 'Project(.*) = ' "$solution_path")
while read -r project
do
	fields=${project#*= }
	project_name=$(unquote $(awk -F', ' '{ print $1 }' <<< "$fields"))
	dos_path=$(unquote $(awk -F', ' '{ print $2 }' <<< "$fields"))
	project_path=$(dos2unix_path "$dos_path")
	dictionary_insert "$solution_cache" "$project_name" "$project_path"
done <<< "$projects"

printf "Done.\n\n"

