#!/bin/bash

source detail/utils
source detail/dictionary


#
# Parameters

solution_path=$1
solution_cache=$2


#
# Main

check_dir $(dirname "$solution_cache")

if [ ! "$solution_path" -nt "$solution_cache" ]
then
	exit
fi

version=$(detail/vs_version "$solution_path")
if [ -z "$version" ]
then
	printf_vdev_error 'failed to detect solution version'
	exit 1
fi

dictionary_insert "$solution_cache" 'version' "$version"

