#!/bin/bash

source detail/constants
source detail/dictionary


#
# Parameters

paths_file=$1


#
# Main

if [ ! -f "$paths_file" ]
then
	new_path_file=true
fi

found_disk=$(detail/detect-volume "$VIRTUAL_DEV_WORKING_DIR")
guest_root_dir=$(dictionary-find "$paths_file" 'guest_root_dir')
if [ $? == 0 ] && [ "$found_disk" == "$guest_root_dir" ]
then
	exit
fi

guest_vdev_guest_dir="$found_disk/$VIRTUAL_DEV_WORKSPACE_NAME/$GUEST_DIR"

dictionary-insert "$paths_file" 'guest_root_dir' "$found_disk"
dictionary-insert "$paths_file" 'guest_msbuild_bat' "$guest_vdev_guest_dir/msbuild.bat"
dictionary-insert "$paths_file" 'guest_run_bat' "$guest_vdev_guest_dir/run.bat"
dictionary-insert "$paths_file" 'guest_execute_bat' "$guest_vdev_guest_dir/execute.bat"

if [ "$new_path_file" != true ]
then
	exit 2
fi

