#!/bin/bash

source detail/constants
source detail/utils
source detail/dictionary


#
# Parameters

workspace_id_path=$1


#
# Main

vdev_vm_file="$VIRTUAL_DEV_WORKSPACE_DIR/$VM_FILE"
dictionary-load "$vdev_vm_file" 'vm'

# waiting for the service to be available

while [ true ]
do
	output=$(detail/"$vm"/execute 'net.exe' 'use')
	if [ $? == 1 ]
	then
		exit 1
	fi

	disks=$(grep [A-Z]: <<< "$output" | awk '{ print $1 }')
	if [ ! -z "$disks" ]
	then
		break
	fi

	sleep 2
done


# searching disk with current project
check-workspace-id "$workspace_id_path"
workspace_id=$(get-workspace-id "$workspace_id_path")
workspace_id_relative_path="$VIRTUAL_DEV_WORKSPACE_NAME\\$VIRTUAL_DEV_WORKSPACE_ID_FILE"
while read -r disk
do
	output=$(detail/"$vm"/execute 'cmd.exe' '/Q' '/C' 'type' "$disk\\$workspace_id_relative_path" 2>&1 | trim-eoln) || exit 1
	if [ $? == 1 ]
	then
		exit 1
	fi

	if [ "$output" == "$workspace_id" ]
	then
		printf '%s\n' "$disk"
		break
	fi
done <<< "$disks"

