#!/bin/bash

source detail/constants
source detail/utils
source detail/dictionary


#
# Parameters

id_dir=$1


#
# Main

vdev_vm_file="$VIRTUAL_DEV_WORKSPACE_DIR/$VM_FILE"
dictionary-load "$vdev_vm_file" 'vm'

# waiting for the service to be available

while [ true ]
do
	output=$(detail/"$vm"/execute 'net.exe' 'use')
	if [ $? == 1 ]
	then
		exit 1
	fi

	disks=$(grep [A-Z]: <<< "$output" | awk '{ print $1 }')
	if [ ! -z "$disks" ]
	then
		break
	fi

	sleep 2
done


# searching disk with current project

id="vdevid$RANDOM"
id_path="$id_dir/$id"
touch "$id_path"
trap "rm -f \"$id_path\"" EXIT

while read -r disk
do
	output=$(detail/"$vm"/execute 'cmd.exe' '/Q' '/C' "if exist $disk\\$id (echo 1) else (echo 0)" | trim-eoln) || exit 1
	if [ $? == 1 ]
	then
		exit 1
	fi

	if [ $output == '1' ]
	then
		printf '%s\n' "$disk"
		break
	fi
done <<< "$disks"

