#!/bin/bash

guest_name=$1
user=$2
password=$3


shift 3
/usr/local/bin/VBoxManage guestcontrol "$guest_name" execute --image "cmd.exe" --username "$user" --password "$password" --wait-exit --wait-stdout --wait-stderr "/E:ON" "/Q" "/C" "$@"

