#!/bin/bash

source detail/utils


id=$(detail/generateid)
trap "rm -f \"vdev/$id\"" EXIT

# waiting for the service to be available
while [ true ]
do
	output=$(detail/"$vm"/execute net use)
	if [ $? -eq 1 ]
	then
		exit 1
	fi

	disks=$(grep [A-Z]: <<< "$output" | awk '{ print $1 }')
	if [ ! -z "$disks" ]
	then
		break
	fi

	sleep 2
done


# searching disk with current project
while read -r disk
do
	output=$(detail/"$vm"/execute "if exist $disk\\vdev\\$id (echo 1) else (echo 0)") || exit 1

	retval="$output"
	if [ $retval = "1" ]
	then
		printf '%s\n' "$disk"
		break
	fi
done <<< "$disks"

