#!/bin/bash

source vdev/detail/utils


guest_name=$1
user=$2
password=$3


VBoxManage startvm "$guest_name" 1> /dev/null || exit 1

checkstr="running"

while [ true ]
do
	output=$(vdev/detail/execute "$guest_name" "$user" "$password" "echo $checkstr" 2> /dev/null)
	if [ $? -eq 0 ] && [ "$output" = "$checkstr" ]
	then
		break
	fi

	sleep 2
done

