#!/bin/bash

source detail/constants
source detail/utils
source detail/dictionary


#
# Parameters

binary_name=$1


#
# Main

vdev_vm_file="$VIRTUAL_DEV_WORKSPACE_DIR/$VM_FILE"
dictionary-load "$vdev_vm_file" 'vm'


printf '\n'
printf-vdev-message 'terminating "%s"...' "$binary_name"
output=$(detail/"$vm"/execute 'taskkill.exe' '/F' '/T' '/IM' "$binary_name" 2>&1)
if [ $? != 0 ]
then
	printf-vdev-error 'failed terminate "%s".\n%s' "$binary_name" "$output"
	exit 1
fi

printf-vdev-message '"%s" terminated' "$binary_name"

