#!/bin/bash


#
# Parameters

solution_path=$1


#
# Main

vs2010=10
vs2012=11
vs2013=12
vs14=14
vs15=2017

version_line=$(grep '^#.*[0-9]\{2,4\}.*' "$solution_path")
version=$(grep -o '[0-9]\{2,4\}' <<< $version_line)
version_variable="vs$version"
printf '%s\n' "${!version_variable}"

