#!/bin/bash

source vdev/detail/utils


solution_path=$1
project_name=$2

record=$(grep 'Project(.*) = "'"$project_name"'".*' "$solution_path")
fields=${record#*= }
quoted=$(awk -F', ' '{ print $2 }' <<< "$fields")
dos_path=${quoted:1:${#quoted}-2}
unix_path=$(dos2unix_path "$dos_path")
printf '%s\n' "$unix_path"

